/* ═══════════════════════════════════════════
   Mock Data — realistic data matching cb_* schemas
   Used when NEXT_PUBLIC_USE_MOCK=true
   ═══════════════════════════════════════════ */

import type {
  Student,
  Contact,
  Staff,
  Attendance,
  TimeEntry,
  StudentNote,
  Book,
  BookLoan,
  RowAssignment,
  CenterSettings,
  StaffSlotAssignment,
  ScheduleOverride,
  ClassroomSection,
} from './types';
import { generateTimeSlots } from './types';

// ── Helpers ────────────────────────────────

const today = new Date().toISOString().split('T')[0];
const now = new Date().toISOString();

function todayAt(h: number, m: number): string {
  const d = new Date();
  d.setHours(h, m, 0, 0);
  return d.toISOString();
}

function addMinutes(iso: string, mins: number): string {
  const d = new Date(iso);
  d.setMinutes(d.getMinutes() + mins);
  return d.toISOString();
}

function daysAgo(n: number): string {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d.toISOString().split('T')[0];
}

function dateAt(dateStr: string, h: number, m: number): string {
  const d = new Date(dateStr + 'T00:00:00');
  d.setHours(h, m, 0, 0);
  return d.toISOString();
}

function twoWeeksFromNow(): string {
  const d = new Date();
  d.setDate(d.getDate() + 14);
  return d.toISOString().split('T')[0];
}

// ── Students (matches cb_students schema) ──

export const MOCK_STUDENTS: Student[] = [
  {
    id: 1, system_id: 'STU-001', clickup_task_id: 'abc001',
    first_name: 'Alice', last_name: 'Johnson', student_id: 'KUM-10001',
    date_of_birth: '2016-03-15', grade_level: '3', school: 'Forest Hills Elementary',
    medical_notes: 'Peanut allergy', enrollment_status: 'Active',
    program_type: 'Paper', subjects: 'Math, Reading',
    enroll_date: '2024-09-01', classroom_position: 'Main Classroom',
    class_schedule_days: 'Monday, Wednesday', class_time_sort_key: 1500,
    current_level_math: 'C', current_level_reading: 'BII',
    ashr_math_status: 'Not Yet ASHR', ashr_reading_status: 'Not Yet ASHR',
    primary_contact_id: 1, billing_contact_id: 1,
    created_at: '2024-09-01T00:00:00Z', updated_at: now,
    pertinent_note: 'Needs iPad tested before leaving',
    tasks: [
      { id: 't1', label: 'Spelling check', completed: false },
      { id: 't2', label: 'Multiplication quiz', completed: false },
    ],
    flags: ['new_concept'],
  },
  {
    id: 2, system_id: 'STU-002', clickup_task_id: 'abc002',
    first_name: 'Ben', last_name: 'Smith', student_id: 'KUM-10002',
    date_of_birth: '2017-07-22', grade_level: '2', school: 'Kenowa Hills Elementary',
    medical_notes: null, enrollment_status: 'Active',
    program_type: 'Paper', subjects: 'Math',
    enroll_date: '2024-10-15', classroom_position: 'Early Learners',
    class_schedule_days: 'Tuesday, Thursday', class_time_sort_key: 1530,
    current_level_math: 'B', current_level_reading: 'AI',
    ashr_math_status: 'Not Yet ASHR', ashr_reading_status: null,
    primary_contact_id: 2, billing_contact_id: 2,
    created_at: '2024-10-15T00:00:00Z', updated_at: now,
  },
  {
    id: 3, system_id: 'STU-003', clickup_task_id: 'abc003',
    first_name: 'Charlie', last_name: 'Davis', student_id: 'KUM-10003',
    date_of_birth: '2015-01-10', grade_level: '4', school: 'Ada Elementary',
    medical_notes: null, enrollment_status: 'Active',
    program_type: 'Paper', subjects: 'Reading',
    enroll_date: '2024-08-01', classroom_position: 'Main Classroom',
    class_schedule_days: 'Monday, Wednesday', class_time_sort_key: 1500,
    current_level_math: 'A', current_level_reading: '7A',
    ashr_math_status: null, ashr_reading_status: 'Not Yet ASHR',
    primary_contact_id: 3, billing_contact_id: 3,
    created_at: '2024-08-01T00:00:00Z', updated_at: now,
  },
  {
    id: 4, system_id: 'STU-004', clickup_task_id: 'abc004',
    first_name: 'Diana', last_name: 'Prince', student_id: 'KUM-10004',
    date_of_birth: '2014-11-05', grade_level: '5', school: 'Forest Hills Elementary',
    medical_notes: null, enrollment_status: 'Active',
    program_type: 'Paper', subjects: 'Math, Reading',
    enroll_date: '2023-09-01', classroom_position: 'Upper Classroom',
    class_schedule_days: 'Monday, Wednesday', class_time_sort_key: 1500,
    current_level_math: 'E', current_level_reading: 'DI',
    ashr_math_status: 'Bronze', ashr_reading_status: 'Not Yet ASHR',
    primary_contact_id: 4, billing_contact_id: 4,
    created_at: '2023-09-01T00:00:00Z', updated_at: now,
    pertinent_note: 'Take multiplication quiz \u2014 flash cards in folder',
    tasks: [
      { id: 't3', label: 'Flash cards drill', completed: false },
      { id: 't4', label: 'Read aloud assessment', completed: false },
      { id: 't5', label: 'Correction worksheet', completed: false },
    ],
    flags: ['needs_help'],
  },
  {
    id: 5, system_id: 'STU-005', clickup_task_id: 'abc005',
    first_name: 'Evan', last_name: 'Wright', student_id: 'KUM-10005',
    date_of_birth: '2013-05-18', grade_level: '6', school: 'East Grand Rapids MS',
    medical_notes: null, enrollment_status: 'Active',
    program_type: 'Paper', subjects: 'Math',
    enroll_date: '2022-09-01', classroom_position: 'Upper Classroom',
    class_schedule_days: 'Tuesday, Thursday', class_time_sort_key: 1500,
    current_level_math: 'F', current_level_reading: 'EII',
    ashr_math_status: 'Silver', ashr_reading_status: null,
    primary_contact_id: 5, billing_contact_id: 5,
    created_at: '2022-09-01T00:00:00Z', updated_at: now,
  },
  {
    id: 6, system_id: 'STU-006', clickup_task_id: 'abc006',
    first_name: 'Fiona', last_name: 'Glenanne', student_id: 'KUM-10006',
    date_of_birth: '2015-09-12', grade_level: '4', school: 'Kenowa Hills Elementary',
    medical_notes: null, enrollment_status: 'Active',
    program_type: 'Paper', subjects: 'Math, Reading',
    enroll_date: '2024-01-15', classroom_position: 'Main Classroom',
    class_schedule_days: 'Monday, Wednesday', class_time_sort_key: 1500,
    current_level_math: 'CI', current_level_reading: 'CI',
    ashr_math_status: 'Not Yet ASHR', ashr_reading_status: 'Not Yet ASHR',
    primary_contact_id: 6, billing_contact_id: 6,
    created_at: '2024-01-15T00:00:00Z', updated_at: now,
    pertinent_note: 'Mom requested extra reading time today',
    flags: ['new_concept', 'needs_help'],
  },
  {
    id: 7, system_id: 'STU-007', clickup_task_id: 'abc007',
    first_name: 'George', last_name: 'Miller', student_id: 'KUM-10007',
    date_of_birth: '2016-12-01', grade_level: '3', school: 'Forest Hills Elementary',
    medical_notes: null, enrollment_status: 'Active',
    program_type: 'Paper', subjects: 'Math',
    enroll_date: '2024-09-01', classroom_position: 'Main Classroom',
    class_schedule_days: 'Tuesday, Thursday', class_time_sort_key: 1530,
    current_level_math: 'D', current_level_reading: 'B',
    ashr_math_status: 'Not Yet ASHR', ashr_reading_status: null,
    primary_contact_id: 7, billing_contact_id: 7,
    created_at: '2024-09-01T00:00:00Z', updated_at: now,
  },
  {
    id: 8, system_id: 'STU-008', clickup_task_id: 'abc008',
    first_name: 'Hannah', last_name: 'Abbott', student_id: 'KUM-10008',
    date_of_birth: '2017-04-28', grade_level: '2', school: 'Ada Elementary',
    medical_notes: null, enrollment_status: 'Active',
    program_type: 'Paper', subjects: 'Reading',
    enroll_date: '2024-11-01', classroom_position: 'Early Learners',
    class_schedule_days: 'Monday, Wednesday', class_time_sort_key: 1530,
    current_level_math: '2A', current_level_reading: '3A',
    ashr_math_status: null, ashr_reading_status: 'Not Yet ASHR',
    primary_contact_id: 8, billing_contact_id: 8,
    created_at: '2024-11-01T00:00:00Z', updated_at: now,
  },
  {
    id: 9, system_id: 'STU-009', clickup_task_id: 'abc009',
    first_name: 'Ian', last_name: 'McKellen', student_id: 'KUM-10009',
    date_of_birth: '2014-08-15', grade_level: '5', school: 'East Grand Rapids MS',
    medical_notes: 'Asthma — inhaler in backpack', enrollment_status: 'Active',
    program_type: 'Paper', subjects: 'Math, Reading',
    enroll_date: '2023-01-15', classroom_position: 'Upper Classroom',
    class_schedule_days: 'Tuesday, Thursday', class_time_sort_key: 1600,
    current_level_math: 'G', current_level_reading: 'F',
    ashr_math_status: 'Gold', ashr_reading_status: 'Bronze',
    primary_contact_id: 9, billing_contact_id: 9,
    created_at: '2023-01-15T00:00:00Z', updated_at: now,
  },
  {
    id: 10, system_id: 'STU-010', clickup_task_id: 'abc010',
    first_name: 'Jack', last_name: 'Sparrow', student_id: 'KUM-10010',
    date_of_birth: '2016-06-20', grade_level: '3', school: 'Kenowa Hills Elementary',
    medical_notes: null, enrollment_status: 'Active',
    program_type: 'Paper', subjects: 'Math',
    enroll_date: '2024-09-01', classroom_position: 'Main Classroom',
    class_schedule_days: 'Monday, Wednesday', class_time_sort_key: 1530,
    current_level_math: 'B', current_level_reading: 'C',
    ashr_math_status: 'Not Yet ASHR', ashr_reading_status: null,
    primary_contact_id: 10, billing_contact_id: 10,
    created_at: '2024-09-01T00:00:00Z', updated_at: now,
  },
  {
    id: 11, system_id: 'STU-011', clickup_task_id: 'abc011',
    first_name: 'Kelly', last_name: 'Clarkson', student_id: 'KUM-10011',
    date_of_birth: '2015-02-14', grade_level: '4', school: 'Forest Hills Elementary',
    medical_notes: null, enrollment_status: 'Active',
    program_type: 'Paper', subjects: 'Reading',
    enroll_date: '2024-03-01', classroom_position: 'Main Classroom',
    class_schedule_days: 'Tuesday, Thursday', class_time_sort_key: 1500,
    current_level_math: 'C', current_level_reading: 'B',
    ashr_math_status: null, ashr_reading_status: 'Not Yet ASHR',
    primary_contact_id: 11, billing_contact_id: 11,
    created_at: '2024-03-01T00:00:00Z', updated_at: now,
  },
  {
    id: 12, system_id: 'STU-012', clickup_task_id: 'abc012',
    first_name: 'Liam', last_name: 'Neeson', student_id: 'KUM-10012',
    date_of_birth: '2014-10-30', grade_level: '5', school: 'Ada Elementary',
    medical_notes: null, enrollment_status: 'Active',
    program_type: 'Paper', subjects: 'Math',
    enroll_date: '2023-09-01', classroom_position: 'Upper Classroom',
    class_schedule_days: 'Monday, Wednesday', class_time_sort_key: 1600,
    current_level_math: 'E', current_level_reading: 'D',
    ashr_math_status: 'Bronze', ashr_reading_status: null,
    primary_contact_id: 12, billing_contact_id: 12,
    created_at: '2023-09-01T00:00:00Z', updated_at: now,
  },
  {
    id: 13, system_id: 'STU-013', clickup_task_id: 'abc013',
    first_name: 'Mia', last_name: 'Farrow', student_id: 'KUM-10013',
    date_of_birth: '2017-12-05', grade_level: '2', school: 'Forest Hills Elementary',
    medical_notes: null, enrollment_status: 'Active',
    program_type: 'Paper', subjects: 'Reading',
    enroll_date: '2025-01-15', classroom_position: 'Early Learners',
    class_schedule_days: 'Tuesday, Thursday', class_time_sort_key: 1500,
    current_level_math: 'A', current_level_reading: '7A',
    ashr_math_status: null, ashr_reading_status: 'Not Yet ASHR',
    primary_contact_id: 13, billing_contact_id: 13,
    created_at: '2025-01-15T00:00:00Z', updated_at: now,
  },
  {
    id: 14, system_id: 'STU-014', clickup_task_id: 'abc014',
    first_name: 'Noah', last_name: 'Ark', student_id: 'KUM-10014',
    date_of_birth: '2015-07-07', grade_level: '4', school: 'Kenowa Hills Elementary',
    medical_notes: null, enrollment_status: 'Active',
    program_type: 'Paper', subjects: 'Math, Reading',
    enroll_date: '2024-09-01', classroom_position: 'Main Classroom',
    class_schedule_days: 'Monday, Wednesday', class_time_sort_key: 1600,
    current_level_math: 'C', current_level_reading: 'B',
    ashr_math_status: 'Not Yet ASHR', ashr_reading_status: 'Not Yet ASHR',
    primary_contact_id: 14, billing_contact_id: 14,
    created_at: '2024-09-01T00:00:00Z', updated_at: now,
    pertinent_note: 'Spelling check before checkout',
    tasks: [
      { id: 't6', label: 'Spelling check', completed: false },
    ],
  },
  {
    id: 15, system_id: 'STU-015', clickup_task_id: 'abc015',
    first_name: 'Olivia', last_name: 'Pope', student_id: 'KUM-10015',
    date_of_birth: '2014-03-25', grade_level: '5', school: 'East Grand Rapids MS',
    medical_notes: null, enrollment_status: 'Active',
    program_type: 'Paper', subjects: 'Math',
    enroll_date: '2023-06-01', classroom_position: 'Upper Classroom',
    class_schedule_days: 'Tuesday, Thursday', class_time_sort_key: 1630,
    current_level_math: 'D', current_level_reading: 'C',
    ashr_math_status: 'Not Yet ASHR', ashr_reading_status: null,
    primary_contact_id: 15, billing_contact_id: 15,
    created_at: '2023-06-01T00:00:00Z', updated_at: now,
  },
  {
    id: 16, system_id: 'STU-016', clickup_task_id: 'abc016',
    first_name: 'Peter', last_name: 'Parker', student_id: 'KUM-10016',
    date_of_birth: '2013-08-10', grade_level: '6', school: 'East Grand Rapids MS',
    medical_notes: null, enrollment_status: 'Active',
    program_type: 'Paper', subjects: 'Reading',
    enroll_date: '2022-01-15', classroom_position: 'Upper Classroom',
    class_schedule_days: 'Monday, Wednesday', class_time_sort_key: 1630,
    current_level_math: 'E', current_level_reading: 'F',
    ashr_math_status: null, ashr_reading_status: 'Silver',
    primary_contact_id: 16, billing_contact_id: 16,
    created_at: '2022-01-15T00:00:00Z', updated_at: now,
  },
  // Additional students to fill near-capacity (matching prototype v5)
  {
    id: 17, system_id: 'STU-017', clickup_task_id: null,
    first_name: 'Quinn', last_name: 'Harris', student_id: 'KUM-10017',
    date_of_birth: '2015-10-15', grade_level: '4', school: 'Forest Hills Elementary',
    medical_notes: null, enrollment_status: 'Active',
    program_type: 'Paper', subjects: 'Math, Reading',
    enroll_date: '2024-10-15', classroom_position: 'Main Classroom',
    class_schedule_days: 'Monday, Wednesday', class_time_sort_key: 1600,
    current_level_math: 'D', current_level_reading: 'CI',
    ashr_math_status: null, ashr_reading_status: null,
    primary_contact_id: null, billing_contact_id: null,
    created_at: '2024-10-15T00:00:00Z', updated_at: now,
  },
  {
    id: 18, system_id: 'STU-018', clickup_task_id: null,
    first_name: 'Ruby', last_name: 'Chen', student_id: 'KUM-10018',
    date_of_birth: '2018-01-05', grade_level: '1', school: 'Ada Elementary',
    medical_notes: null, enrollment_status: 'Active',
    program_type: 'Paper', subjects: 'Math',
    enroll_date: '2025-01-05', classroom_position: 'Main Classroom',
    class_schedule_days: 'Monday, Thursday', class_time_sort_key: 1600,
    current_level_math: 'B', current_level_reading: 'AI',
    ashr_math_status: null, ashr_reading_status: null,
    primary_contact_id: null, billing_contact_id: null,
    created_at: '2025-01-05T00:00:00Z', updated_at: now,
  },
  {
    id: 19, system_id: 'STU-019', clickup_task_id: null,
    first_name: 'Sam', last_name: 'Taylor', student_id: 'KUM-10019',
    date_of_birth: '2016-08-10', grade_level: '3', school: 'Kenowa Hills Elementary',
    medical_notes: null, enrollment_status: 'Active',
    program_type: 'Paper', subjects: 'Math, Reading',
    enroll_date: '2024-08-10', classroom_position: 'Main Classroom',
    class_schedule_days: 'Tuesday, Thursday', class_time_sort_key: 1530,
    current_level_math: 'C', current_level_reading: 'BII',
    ashr_math_status: null, ashr_reading_status: null,
    primary_contact_id: null, billing_contact_id: null,
    created_at: '2024-08-10T00:00:00Z', updated_at: now,
  },
  {
    id: 20, system_id: 'STU-020', clickup_task_id: null,
    first_name: 'Tessa', last_name: 'Wong', student_id: 'KUM-10020',
    date_of_birth: '2019-02-10', grade_level: 'PK2', school: null,
    medical_notes: null, enrollment_status: 'Active',
    program_type: 'Paper', subjects: 'Reading',
    enroll_date: '2025-02-10', classroom_position: 'Early Learners',
    class_schedule_days: 'Monday, Wednesday', class_time_sort_key: 1600,
    current_level_math: '3A', current_level_reading: '4A',
    ashr_math_status: null, ashr_reading_status: null,
    primary_contact_id: null, billing_contact_id: null,
    created_at: '2025-02-10T00:00:00Z', updated_at: now,
  },
  {
    id: 21, system_id: 'STU-021', clickup_task_id: null,
    first_name: 'Umar', last_name: 'Patel', student_id: 'KUM-10021',
    date_of_birth: '2013-08-20', grade_level: '8', school: 'East Grand Rapids MS',
    medical_notes: null, enrollment_status: 'Active',
    program_type: 'Digital', subjects: 'Math',
    enroll_date: '2023-08-20', classroom_position: 'Upper Classroom',
    class_schedule_days: 'Monday, Wednesday, Thursday', class_time_sort_key: 1530,
    current_level_math: 'F', current_level_reading: 'E',
    ashr_math_status: 'Bronze', ashr_reading_status: null,
    primary_contact_id: null, billing_contact_id: null,
    created_at: '2023-08-20T00:00:00Z', updated_at: now,
  },
  {
    id: 22, system_id: 'STU-022', clickup_task_id: null,
    first_name: 'Violet', last_name: 'Brooks', student_id: 'KUM-10022',
    date_of_birth: '2017-11-01', grade_level: '2', school: 'Forest Hills Elementary',
    medical_notes: null, enrollment_status: 'Active',
    program_type: 'Paper', subjects: 'Math, Reading',
    enroll_date: '2024-11-01', classroom_position: 'Main Classroom',
    class_schedule_days: 'Monday, Wednesday', class_time_sort_key: 1600,
    current_level_math: 'A', current_level_reading: '7A',
    ashr_math_status: null, ashr_reading_status: null,
    primary_contact_id: null, billing_contact_id: null,
    created_at: '2024-11-01T00:00:00Z', updated_at: now,
  },
  {
    id: 23, system_id: 'STU-023', clickup_task_id: null,
    first_name: 'Will', last_name: 'Jackson', student_id: 'KUM-10023',
    date_of_birth: '2014-05-20', grade_level: '5', school: 'Ada Elementary',
    medical_notes: null, enrollment_status: 'Active',
    program_type: 'Paper', subjects: 'Math',
    enroll_date: '2024-05-20', classroom_position: 'Main Classroom',
    class_schedule_days: 'Tuesday, Thursday', class_time_sort_key: 1530,
    current_level_math: 'D', current_level_reading: 'C',
    ashr_math_status: null, ashr_reading_status: null,
    primary_contact_id: null, billing_contact_id: null,
    created_at: '2024-05-20T00:00:00Z', updated_at: now,
  },
  {
    id: 24, system_id: 'STU-024', clickup_task_id: null,
    first_name: 'Xena', last_name: 'Lopez', student_id: 'KUM-10024',
    date_of_birth: '2018-01-15', grade_level: '1', school: 'Forest Hills Elementary',
    medical_notes: null, enrollment_status: 'Active',
    program_type: 'Paper', subjects: 'Reading',
    enroll_date: '2025-01-15', classroom_position: 'Main Classroom',
    class_schedule_days: 'Monday, Thursday', class_time_sort_key: 1600,
    current_level_math: 'B', current_level_reading: 'AI',
    ashr_math_status: null, ashr_reading_status: null,
    primary_contact_id: null, billing_contact_id: null,
    created_at: '2025-01-15T00:00:00Z', updated_at: now,
  },
  {
    id: 25, system_id: 'STU-025', clickup_task_id: null,
    first_name: 'Yuki', last_name: 'Tanaka', student_id: 'KUM-10025',
    date_of_birth: '2015-02-28', grade_level: '6', school: 'East Grand Rapids MS',
    medical_notes: null, enrollment_status: 'Active',
    program_type: 'Paper', subjects: 'Math, Reading',
    enroll_date: '2024-02-28', classroom_position: 'Main Classroom',
    class_schedule_days: 'Monday, Wednesday', class_time_sort_key: 1530,
    current_level_math: 'E', current_level_reading: 'DI',
    ashr_math_status: null, ashr_reading_status: null,
    primary_contact_id: null, billing_contact_id: null,
    created_at: '2024-02-28T00:00:00Z', updated_at: now,
  },
  {
    id: 26, system_id: 'STU-026', clickup_task_id: null,
    first_name: 'Zara', last_name: 'Ahmed', student_id: 'KUM-10026',
    date_of_birth: '2019-02-20', grade_level: 'PK1', school: null,
    medical_notes: null, enrollment_status: 'Active',
    program_type: 'Paper', subjects: 'Math',
    enroll_date: '2025-02-20', classroom_position: 'Early Learners',
    class_schedule_days: 'Tuesday, Thursday', class_time_sort_key: 1600,
    current_level_math: '2A', current_level_reading: '3A',
    ashr_math_status: null, ashr_reading_status: null,
    primary_contact_id: null, billing_contact_id: null,
    created_at: '2025-02-20T00:00:00Z', updated_at: now,
  },
  {
    id: 27, system_id: 'STU-027', clickup_task_id: null,
    first_name: 'Aiden', last_name: 'Murphy', student_id: 'KUM-10027',
    date_of_birth: '2016-09-20', grade_level: '3', school: 'Kenowa Hills Elementary',
    medical_notes: null, enrollment_status: 'Active',
    program_type: 'Paper', subjects: 'Math, Reading',
    enroll_date: '2024-09-20', classroom_position: 'Main Classroom',
    class_schedule_days: 'Monday, Wednesday, Thursday', class_time_sort_key: 1530,
    current_level_math: 'C', current_level_reading: 'BII',
    ashr_math_status: null, ashr_reading_status: null,
    primary_contact_id: null, billing_contact_id: null,
    created_at: '2024-09-20T00:00:00Z', updated_at: now,
  },
  {
    id: 28, system_id: 'STU-028', clickup_task_id: null,
    first_name: 'Bella', last_name: 'Rivera', student_id: 'KUM-10028',
    date_of_birth: '2015-07-15', grade_level: '4', school: 'Forest Hills Elementary',
    medical_notes: null, enrollment_status: 'Active',
    program_type: 'Paper', subjects: 'Reading',
    enroll_date: '2024-07-15', classroom_position: 'Main Classroom',
    class_schedule_days: 'Monday, Wednesday', class_time_sort_key: 1600,
    current_level_math: 'D', current_level_reading: 'CI',
    ashr_math_status: null, ashr_reading_status: null,
    primary_contact_id: null, billing_contact_id: null,
    created_at: '2024-07-15T00:00:00Z', updated_at: now,
  },
  {
    id: 29, system_id: 'STU-029', clickup_task_id: null,
    first_name: 'Carter', last_name: 'Lee', student_id: 'KUM-10029',
    date_of_birth: '2012-03-10', grade_level: '9', school: 'East Grand Rapids HS',
    medical_notes: null, enrollment_status: 'Active',
    program_type: 'Digital', subjects: 'Math',
    enroll_date: '2023-03-10', classroom_position: 'Upper Classroom',
    class_schedule_days: 'Monday, Wednesday', class_time_sort_key: 1530,
    current_level_math: 'G', current_level_reading: 'F',
    ashr_math_status: 'Silver', ashr_reading_status: null,
    primary_contact_id: null, billing_contact_id: null,
    created_at: '2023-03-10T00:00:00Z', updated_at: now,
  },
  {
    id: 30, system_id: 'STU-030', clickup_task_id: null,
    first_name: 'Daisy', last_name: 'Kim', student_id: 'KUM-10030',
    date_of_birth: '2017-12-10', grade_level: '2', school: 'Ada Elementary',
    medical_notes: null, enrollment_status: 'Active',
    program_type: 'Paper', subjects: 'Math, Reading',
    enroll_date: '2024-12-10', classroom_position: 'Main Classroom',
    class_schedule_days: 'Tuesday, Thursday', class_time_sort_key: 1600,
    current_level_math: 'A', current_level_reading: '7A',
    ashr_math_status: null, ashr_reading_status: null,
    primary_contact_id: null, billing_contact_id: null,
    created_at: '2024-12-10T00:00:00Z', updated_at: now,
  },
  {
    id: 31, system_id: 'STU-031', clickup_task_id: null,
    first_name: 'Eli', last_name: 'Brown', student_id: 'KUM-10031',
    date_of_birth: '2015-01-15', grade_level: '6', school: 'East Grand Rapids MS',
    medical_notes: 'Latex allergy', enrollment_status: 'Active',
    program_type: 'Paper', subjects: 'Math',
    enroll_date: '2024-01-15', classroom_position: 'Main Classroom',
    class_schedule_days: 'Monday, Thursday', class_time_sort_key: 1530,
    current_level_math: 'E', current_level_reading: 'DI',
    ashr_math_status: null, ashr_reading_status: null,
    primary_contact_id: null, billing_contact_id: null,
    created_at: '2024-01-15T00:00:00Z', updated_at: now,
  },
  {
    id: 32, system_id: 'STU-032', clickup_task_id: null,
    first_name: 'Faith', last_name: 'Wilson', student_id: 'KUM-10032',
    date_of_birth: '2018-01-25', grade_level: '1', school: 'Forest Hills Elementary',
    medical_notes: null, enrollment_status: 'Active',
    program_type: 'Paper', subjects: 'Reading',
    enroll_date: '2025-01-25', classroom_position: 'Main Classroom',
    class_schedule_days: 'Monday, Wednesday', class_time_sort_key: 1600,
    current_level_math: 'B', current_level_reading: 'AI',
    ashr_math_status: null, ashr_reading_status: null,
    primary_contact_id: null, billing_contact_id: null,
    created_at: '2025-01-25T00:00:00Z', updated_at: now,
  },
  {
    id: 33, system_id: 'STU-033', clickup_task_id: null,
    first_name: 'Gabe', last_name: 'Martin', student_id: 'KUM-10033',
    date_of_birth: '2016-08-25', grade_level: '3', school: 'Ada Elementary',
    medical_notes: null, enrollment_status: 'Active',
    program_type: 'Paper', subjects: 'Math, Reading',
    enroll_date: '2024-08-25', classroom_position: 'Main Classroom',
    class_schedule_days: 'Tuesday, Thursday', class_time_sort_key: 1530,
    current_level_math: 'C', current_level_reading: 'BII',
    ashr_math_status: null, ashr_reading_status: null,
    primary_contact_id: null, billing_contact_id: null,
    created_at: '2024-08-25T00:00:00Z', updated_at: now,
  },
  {
    id: 34, system_id: 'STU-034', clickup_task_id: null,
    first_name: 'Holly', last_name: 'Scott', student_id: 'KUM-10034',
    date_of_birth: '2013-05-10', grade_level: '8', school: 'East Grand Rapids MS',
    medical_notes: null, enrollment_status: 'Active',
    program_type: 'Paper', subjects: 'Math',
    enroll_date: '2023-05-10', classroom_position: 'Upper Classroom',
    class_schedule_days: 'Monday, Wednesday, Thursday', class_time_sort_key: 1500,
    current_level_math: 'F', current_level_reading: 'E',
    ashr_math_status: 'Bronze', ashr_reading_status: null,
    primary_contact_id: null, billing_contact_id: null,
    created_at: '2023-05-10T00:00:00Z', updated_at: now,
  },
  {
    id: 35, system_id: 'STU-035', clickup_task_id: null,
    first_name: 'Isaac', last_name: 'Young', student_id: 'KUM-10035',
    date_of_birth: '2014-06-15', grade_level: '5', school: 'Kenowa Hills Elementary',
    medical_notes: null, enrollment_status: 'Active',
    program_type: 'Paper', subjects: 'Math, Reading',
    enroll_date: '2024-06-15', classroom_position: 'Main Classroom',
    class_schedule_days: 'Monday, Wednesday', class_time_sort_key: 1600,
    current_level_math: 'D', current_level_reading: 'C',
    ashr_math_status: null, ashr_reading_status: null,
    primary_contact_id: null, billing_contact_id: null,
    created_at: '2024-06-15T00:00:00Z', updated_at: now,
  },
  {
    id: 36, system_id: 'STU-036', clickup_task_id: null,
    first_name: 'Jade', last_name: 'Thomas', student_id: 'KUM-10036',
    date_of_birth: '2019-03-01', grade_level: 'PK2', school: null,
    medical_notes: null, enrollment_status: 'Active',
    program_type: 'Paper', subjects: 'Reading',
    enroll_date: '2025-03-01', classroom_position: 'Early Learners',
    class_schedule_days: 'Monday, Thursday', class_time_sort_key: 1600,
    current_level_math: '3A', current_level_reading: '4A',
    ashr_math_status: null, ashr_reading_status: null,
    primary_contact_id: null, billing_contact_id: null,
    created_at: '2025-03-01T00:00:00Z', updated_at: now,
  },
  {
    id: 37, system_id: 'STU-037', clickup_task_id: null,
    first_name: 'Kai', last_name: 'Nguyen', student_id: 'KUM-10037',
    date_of_birth: '2014-03-20', grade_level: '7', school: 'East Grand Rapids MS',
    medical_notes: null, enrollment_status: 'Active',
    program_type: 'Paper', subjects: 'Math',
    enroll_date: '2024-03-20', classroom_position: 'Main Classroom',
    class_schedule_days: 'Monday, Wednesday', class_time_sort_key: 1530,
    current_level_math: 'E', current_level_reading: 'DI',
    ashr_math_status: null, ashr_reading_status: null,
    primary_contact_id: null, billing_contact_id: null,
    created_at: '2024-03-20T00:00:00Z', updated_at: now,
  },
  {
    id: 38, system_id: 'STU-038', clickup_task_id: null,
    first_name: 'Luna', last_name: 'Garcia', student_id: 'KUM-10038',
    date_of_birth: '2017-11-20', grade_level: '2', school: 'Forest Hills Elementary',
    medical_notes: null, enrollment_status: 'Active',
    program_type: 'Paper', subjects: 'Math, Reading',
    enroll_date: '2024-11-20', classroom_position: 'Main Classroom',
    class_schedule_days: 'Tuesday, Thursday', class_time_sort_key: 1600,
    current_level_math: 'A', current_level_reading: '7A',
    ashr_math_status: null, ashr_reading_status: null,
    primary_contact_id: null, billing_contact_id: null,
    created_at: '2024-11-20T00:00:00Z', updated_at: now,
  },
  {
    id: 39, system_id: 'STU-039', clickup_task_id: null,
    first_name: 'Max', last_name: 'Hall', student_id: 'KUM-10039',
    date_of_birth: '2011-09-01', grade_level: '10', school: 'East Grand Rapids HS',
    medical_notes: null, enrollment_status: 'Active',
    program_type: 'Digital', subjects: 'Math, Reading',
    enroll_date: '2022-09-01', classroom_position: 'Upper Classroom',
    class_schedule_days: 'Monday, Wednesday', class_time_sort_key: 1530,
    current_level_math: 'G', current_level_reading: 'GII',
    ashr_math_status: 'Gold', ashr_reading_status: 'Silver',
    primary_contact_id: null, billing_contact_id: null,
    created_at: '2022-09-01T00:00:00Z', updated_at: now,
  },
  {
    id: 40, system_id: 'STU-040', clickup_task_id: null,
    first_name: 'Nora', last_name: 'Allen', student_id: 'KUM-10040',
    date_of_birth: '2018-02-05', grade_level: 'K', school: 'Ada Elementary',
    medical_notes: null, enrollment_status: 'Active',
    program_type: 'Paper', subjects: 'Math',
    enroll_date: '2025-02-05', classroom_position: 'Main Classroom',
    class_schedule_days: 'Monday, Thursday', class_time_sort_key: 1600,
    current_level_math: 'B', current_level_reading: 'AI',
    ashr_math_status: null, ashr_reading_status: null,
    primary_contact_id: null, billing_contact_id: null,
    created_at: '2025-02-05T00:00:00Z', updated_at: now,
  },
  {
    id: 41, system_id: 'STU-041', clickup_task_id: null,
    first_name: 'Oscar', last_name: 'Wright', student_id: 'KUM-10041',
    date_of_birth: '2016-10-05', grade_level: '3', school: 'Kenowa Hills Elementary',
    medical_notes: null, enrollment_status: 'Active',
    program_type: 'Paper', subjects: 'Reading',
    enroll_date: '2024-10-05', classroom_position: 'Main Classroom',
    class_schedule_days: 'Monday, Wednesday', class_time_sort_key: 1530,
    current_level_math: 'C', current_level_reading: 'BII',
    ashr_math_status: null, ashr_reading_status: null,
    primary_contact_id: null, billing_contact_id: null,
    created_at: '2024-10-05T00:00:00Z', updated_at: now,
  },
  {
    id: 42, system_id: 'STU-042', clickup_task_id: null,
    first_name: 'Penny', last_name: 'Clark', student_id: 'KUM-10042',
    date_of_birth: '2015-07-01', grade_level: '4', school: 'Forest Hills Elementary',
    medical_notes: null, enrollment_status: 'Active',
    program_type: 'Paper', subjects: 'Math, Reading',
    enroll_date: '2024-07-01', classroom_position: 'Main Classroom',
    class_schedule_days: 'Tuesday, Thursday', class_time_sort_key: 1600,
    current_level_math: 'D', current_level_reading: 'CI',
    ashr_math_status: null, ashr_reading_status: null,
    primary_contact_id: null, billing_contact_id: null,
    created_at: '2024-07-01T00:00:00Z', updated_at: now,
  },
  {
    id: 43, system_id: 'STU-043', clickup_task_id: null,
    first_name: 'Ryan', last_name: 'Foster', student_id: 'KUM-10043',
    date_of_birth: '2016-09-25', grade_level: '3', school: 'Ada Elementary',
    medical_notes: null, enrollment_status: 'Active',
    program_type: 'Paper', subjects: 'Math',
    enroll_date: '2024-09-25', classroom_position: 'Main Classroom',
    class_schedule_days: 'Monday, Wednesday', class_time_sort_key: 1530,
    current_level_math: 'C', current_level_reading: 'BII',
    ashr_math_status: null, ashr_reading_status: null,
    primary_contact_id: null, billing_contact_id: null,
    created_at: '2024-09-25T00:00:00Z', updated_at: now,
  },
  {
    id: 44, system_id: 'STU-044', clickup_task_id: null,
    first_name: 'Sofia', last_name: 'Reyes', student_id: 'KUM-10044',
    date_of_birth: '2015-08-05', grade_level: '4', school: 'Kenowa Hills Elementary',
    medical_notes: null, enrollment_status: 'Active',
    program_type: 'Paper', subjects: 'Math, Reading',
    enroll_date: '2024-08-05', classroom_position: 'Main Classroom',
    class_schedule_days: 'Monday, Thursday', class_time_sort_key: 1600,
    current_level_math: 'D', current_level_reading: 'CI',
    ashr_math_status: null, ashr_reading_status: null,
    primary_contact_id: null, billing_contact_id: null,
    created_at: '2024-08-05T00:00:00Z', updated_at: now,
  },
  {
    id: 45, system_id: 'STU-045', clickup_task_id: null,
    first_name: 'Tyler', last_name: 'Moore', student_id: 'KUM-10045',
    date_of_birth: '2018-01-08', grade_level: '1', school: 'Forest Hills Elementary',
    medical_notes: null, enrollment_status: 'Active',
    program_type: 'Paper', subjects: 'Reading',
    enroll_date: '2025-01-08', classroom_position: 'Main Classroom',
    class_schedule_days: 'Monday, Wednesday', class_time_sort_key: 1600,
    current_level_math: 'B', current_level_reading: 'AI',
    ashr_math_status: null, ashr_reading_status: null,
    primary_contact_id: null, billing_contact_id: null,
    created_at: '2025-01-08T00:00:00Z', updated_at: now,
  },
  {
    id: 46, system_id: 'STU-046', clickup_task_id: null,
    first_name: 'Uma', last_name: 'Sharma', student_id: 'KUM-10046',
    date_of_birth: '2015-04-10', grade_level: '6', school: 'East Grand Rapids MS',
    medical_notes: null, enrollment_status: 'Active',
    program_type: 'Paper', subjects: 'Math',
    enroll_date: '2024-04-10', classroom_position: 'Main Classroom',
    class_schedule_days: 'Tuesday, Thursday', class_time_sort_key: 1530,
    current_level_math: 'E', current_level_reading: 'DI',
    ashr_math_status: null, ashr_reading_status: null,
    primary_contact_id: null, billing_contact_id: null,
    created_at: '2024-04-10T00:00:00Z', updated_at: now,
  },
  {
    id: 47, system_id: 'STU-047', clickup_task_id: null,
    first_name: 'Vera', last_name: 'Stone', student_id: 'KUM-10047',
    date_of_birth: '2017-11-10', grade_level: '2', school: 'Ada Elementary',
    medical_notes: null, enrollment_status: 'Active',
    program_type: 'Paper', subjects: 'Math, Reading',
    enroll_date: '2024-11-10', classroom_position: 'Main Classroom',
    class_schedule_days: 'Monday, Wednesday', class_time_sort_key: 1600,
    current_level_math: 'A', current_level_reading: '7A',
    ashr_math_status: null, ashr_reading_status: null,
    primary_contact_id: null, billing_contact_id: null,
    created_at: '2024-11-10T00:00:00Z', updated_at: now,
  },
  {
    id: 48, system_id: 'STU-048', clickup_task_id: null,
    first_name: 'Wyatt', last_name: 'Cole', student_id: 'KUM-10048',
    date_of_birth: '2016-10-20', grade_level: '3', school: 'Kenowa Hills Elementary',
    medical_notes: null, enrollment_status: 'Active',
    program_type: 'Paper', subjects: 'Math',
    enroll_date: '2024-10-20', classroom_position: 'Main Classroom',
    class_schedule_days: 'Monday, Thursday', class_time_sort_key: 1530,
    current_level_math: 'C', current_level_reading: 'B',
    ashr_math_status: null, ashr_reading_status: null,
    primary_contact_id: null, billing_contact_id: null,
    created_at: '2024-10-20T00:00:00Z', updated_at: now,
  },
  {
    id: 49, system_id: 'STU-049', clickup_task_id: null,
    first_name: 'Zoey', last_name: 'Price', student_id: 'KUM-10049',
    date_of_birth: '2014-06-20', grade_level: '5', school: 'Forest Hills Elementary',
    medical_notes: null, enrollment_status: 'Active',
    program_type: 'Paper', subjects: 'Reading',
    enroll_date: '2024-06-20', classroom_position: 'Main Classroom',
    class_schedule_days: 'Monday, Wednesday', class_time_sort_key: 1600,
    current_level_math: 'D', current_level_reading: 'CI',
    ashr_math_status: null, ashr_reading_status: null,
    primary_contact_id: null, billing_contact_id: null,
    created_at: '2024-06-20T00:00:00Z', updated_at: now,
  },
  {
    id: 50, system_id: 'STU-050', clickup_task_id: null,
    first_name: 'Amir', last_name: 'Khan', student_id: 'KUM-10050',
    date_of_birth: '2018-02-15', grade_level: '1', school: 'Ada Elementary',
    medical_notes: null, enrollment_status: 'Active',
    program_type: 'Paper', subjects: 'Math, Reading',
    enroll_date: '2025-02-15', classroom_position: 'Main Classroom',
    class_schedule_days: 'Tuesday, Thursday', class_time_sort_key: 1600,
    current_level_math: 'B', current_level_reading: 'AI',
    ashr_math_status: null, ashr_reading_status: null,
    primary_contact_id: null, billing_contact_id: null,
    created_at: '2025-02-15T00:00:00Z', updated_at: now,
  },
  {
    id: 51, system_id: 'STU-051', clickup_task_id: null,
    first_name: 'Brooke', last_name: 'Adams', student_id: 'KUM-10051',
    date_of_birth: '2015-02-10', grade_level: '6', school: 'East Grand Rapids MS',
    medical_notes: null, enrollment_status: 'Active',
    program_type: 'Paper', subjects: 'Math',
    enroll_date: '2024-02-10', classroom_position: 'Main Classroom',
    class_schedule_days: 'Monday, Wednesday', class_time_sort_key: 1530,
    current_level_math: 'E', current_level_reading: 'D',
    ashr_math_status: null, ashr_reading_status: null,
    primary_contact_id: null, billing_contact_id: null,
    created_at: '2024-02-10T00:00:00Z', updated_at: now,
  },
  {
    id: 52, system_id: 'STU-052', clickup_task_id: null,
    first_name: 'Caleb', last_name: 'Reed', student_id: 'KUM-10052',
    date_of_birth: '2016-09-10', grade_level: '3', school: 'Kenowa Hills Elementary',
    medical_notes: null, enrollment_status: 'Active',
    program_type: 'Paper', subjects: 'Math, Reading',
    enroll_date: '2024-09-10', classroom_position: 'Main Classroom',
    class_schedule_days: 'Monday, Thursday', class_time_sort_key: 1600,
    current_level_math: 'C', current_level_reading: 'BII',
    ashr_math_status: null, ashr_reading_status: null,
    primary_contact_id: null, billing_contact_id: null,
    created_at: '2024-09-10T00:00:00Z', updated_at: now,
  },
  {
    id: 53, system_id: 'STU-053', clickup_task_id: null,
    first_name: 'Dina', last_name: 'Ross', student_id: 'KUM-10053',
    date_of_birth: '2017-12-20', grade_level: '2', school: 'Forest Hills Elementary',
    medical_notes: null, enrollment_status: 'Active',
    program_type: 'Paper', subjects: 'Reading',
    enroll_date: '2024-12-20', classroom_position: 'Main Classroom',
    class_schedule_days: 'Monday, Wednesday', class_time_sort_key: 1600,
    current_level_math: 'A', current_level_reading: '7A',
    ashr_math_status: null, ashr_reading_status: null,
    primary_contact_id: null, billing_contact_id: null,
    created_at: '2024-12-20T00:00:00Z', updated_at: now,
  },
  {
    id: 54, system_id: 'STU-054', clickup_task_id: null,
    first_name: 'Ezra', last_name: 'Bell', student_id: 'KUM-10054',
    date_of_birth: '2014-05-05', grade_level: '5', school: 'Ada Elementary',
    medical_notes: null, enrollment_status: 'Active',
    program_type: 'Paper', subjects: 'Math',
    enroll_date: '2024-05-05', classroom_position: 'Main Classroom',
    class_schedule_days: 'Tuesday, Thursday', class_time_sort_key: 1530,
    current_level_math: 'D', current_level_reading: 'C',
    ashr_math_status: null, ashr_reading_status: null,
    primary_contact_id: null, billing_contact_id: null,
    created_at: '2024-05-05T00:00:00Z', updated_at: now,
  },
  {
    id: 55, system_id: 'STU-055', clickup_task_id: null,
    first_name: 'Greta', last_name: 'Hoffman', student_id: 'KUM-10055',
    date_of_birth: '2013-07-15', grade_level: '8', school: 'East Grand Rapids MS',
    medical_notes: null, enrollment_status: 'Active',
    program_type: 'Digital', subjects: 'Math, Reading',
    enroll_date: '2023-07-15', classroom_position: 'Upper Classroom',
    class_schedule_days: 'Monday, Wednesday', class_time_sort_key: 1530,
    current_level_math: 'F', current_level_reading: 'E',
    ashr_math_status: 'Bronze', ashr_reading_status: null,
    primary_contact_id: null, billing_contact_id: null,
    created_at: '2023-07-15T00:00:00Z', updated_at: now,
  },
  {
    id: 56, system_id: 'STU-056', clickup_task_id: null,
    first_name: 'Henry', last_name: 'Marsh', student_id: 'KUM-10056',
    date_of_birth: '2016-10-30', grade_level: '3', school: 'Kenowa Hills Elementary',
    medical_notes: null, enrollment_status: 'Active',
    program_type: 'Paper', subjects: 'Math',
    enroll_date: '2024-10-30', classroom_position: 'Main Classroom',
    class_schedule_days: 'Monday, Wednesday', class_time_sort_key: 1600,
    current_level_math: 'C', current_level_reading: 'BII',
    ashr_math_status: null, ashr_reading_status: null,
    primary_contact_id: null, billing_contact_id: null,
    created_at: '2024-10-30T00:00:00Z', updated_at: now,
  },
  {
    id: 57, system_id: 'STU-057', clickup_task_id: null,
    first_name: 'Ivy', last_name: 'Grant', student_id: 'KUM-10057',
    date_of_birth: '2018-01-30', grade_level: '1', school: 'Forest Hills Elementary',
    medical_notes: null, enrollment_status: 'Active',
    program_type: 'Paper', subjects: 'Math, Reading',
    enroll_date: '2025-01-30', classroom_position: 'Main Classroom',
    class_schedule_days: 'Monday, Thursday', class_time_sort_key: 1600,
    current_level_math: 'B', current_level_reading: 'AI',
    ashr_math_status: null, ashr_reading_status: null,
    primary_contact_id: null, billing_contact_id: null,
    created_at: '2025-01-30T00:00:00Z', updated_at: now,
  },
];

// ── Contacts ───────────────────────────────

export const MOCK_CONTACTS: Contact[] = [
  {
    id: 1, system_id: 'CON-001', clickup_task_id: 'con001',
    first_name: 'Sarah', last_name: 'Johnson',
    email: 'sarah.johnson@email.com', phone: '616-555-1001',
    relationship_to_students: 'Mother', preferred_contact_method: 'Text',
    portal_access_enabled: 1, wp_user_id: 42,
    created_at: '2024-09-01T00:00:00Z', updated_at: now,
  },
  {
    id: 2, system_id: 'CON-002', clickup_task_id: 'con002',
    first_name: 'Tom', last_name: 'Smith',
    email: 'tom.smith@email.com', phone: '616-555-1002',
    relationship_to_students: 'Father', preferred_contact_method: 'Call',
    portal_access_enabled: 1, wp_user_id: 43,
    created_at: '2024-10-15T00:00:00Z', updated_at: now,
  },
  {
    id: 3, system_id: 'CON-003', clickup_task_id: 'con003',
    first_name: 'Maria', last_name: 'Davis',
    email: 'maria.davis@email.com', phone: '616-555-1003',
    relationship_to_students: 'Mother', preferred_contact_method: 'Email',
    portal_access_enabled: 1, wp_user_id: 44,
    created_at: '2024-08-01T00:00:00Z', updated_at: now,
  },
];

// ── Staff ──────────────────────────────────

export const MOCK_STAFF: Staff[] = [
  {
    id: 1, clickup_task_id: null,
    full_name: 'Bincy Thomas', email: 'bincy@kumon-grn.com', phone: '616-555-2001',
    address: null, date_of_birth: null,
    role: 'Owner', hire_date: '2020-01-01', wp_user_id: 2,
    pin: '1234', status: 'Active',
    created_at: '2020-01-01T00:00:00Z', updated_at: now,
    scheduled_shift: '2:00 PM - 7:00 PM', assigned_row: null,
  },
  {
    id: 2, clickup_task_id: null,
    full_name: 'Sarah Kim', email: 'sarah.k@kumon-grn.com', phone: '616-555-2002',
    address: null, date_of_birth: null,
    role: 'Instruction Manager', hire_date: '2022-06-01', wp_user_id: 10,
    pin: '2345', status: 'Active',
    created_at: '2022-06-01T00:00:00Z', updated_at: now,
    scheduled_shift: '2:45 PM - 6:30 PM', assigned_row: 'MC',
  },
  {
    id: 3, clickup_task_id: null,
    full_name: 'Jane Doe', email: 'jane.d@kumon-grn.com', phone: '616-555-2003',
    address: null, date_of_birth: null,
    role: 'Teacher', hire_date: '2023-01-15', wp_user_id: 11,
    pin: '3456', status: 'Active',
    created_at: '2023-01-15T00:00:00Z', updated_at: now,
    scheduled_shift: '3:00 PM - 6:00 PM', assigned_row: 'EL',
  },
  {
    id: 4, clickup_task_id: null,
    full_name: 'Mike Rodriguez', email: 'mike.r@kumon-grn.com', phone: '616-555-2004',
    address: null, date_of_birth: null,
    role: 'Teacher', hire_date: '2023-09-01', wp_user_id: 12,
    pin: '4567', status: 'Active',
    created_at: '2023-09-01T00:00:00Z', updated_at: now,
    scheduled_shift: '3:00 PM - 6:00 PM', assigned_row: 'MC',
  },
  {
    id: 5, clickup_task_id: null,
    full_name: 'Leah Martin', email: 'leah.m@kumon-grn.com', phone: '616-555-2005',
    address: null, date_of_birth: null,
    role: 'Teacher', hire_date: '2024-01-15', wp_user_id: 13,
    pin: '5678', status: 'Active',
    created_at: '2024-01-15T00:00:00Z', updated_at: now,
    scheduled_shift: '3:00 PM - 6:00 PM', assigned_row: 'UC',
  },
  {
    id: 6, clickup_task_id: null,
    full_name: 'Chris Park', email: 'chris.p@kumon-grn.com', phone: '616-555-2006',
    address: null, date_of_birth: null,
    role: 'Teacher', hire_date: '2024-09-01', wp_user_id: null,
    pin: '6789', status: 'Active',
    created_at: '2024-09-01T00:00:00Z', updated_at: now,
    scheduled_shift: '3:30 PM - 6:00 PM', assigned_row: 'MC',
  },
  {
    id: 7, clickup_task_id: null,
    full_name: 'Fran Martinez', email: 'fran@kumon-grn.com', phone: '616-555-2007',
    address: null, date_of_birth: null,
    role: 'Center Manager', hire_date: '2021-06-01', wp_user_id: 14,
    pin: '7890', status: 'Active',
    created_at: '2021-06-01T00:00:00Z', updated_at: now,
    scheduled_shift: '2:30 PM - 6:30 PM', assigned_row: null,
  },
  {
    id: 8, clickup_task_id: null,
    full_name: 'Amy Chen', email: 'amy@kumon-grn.com', phone: '616-555-2008',
    address: null, date_of_birth: null,
    role: 'Instruction Manager', hire_date: '2022-01-15', wp_user_id: 15,
    pin: '8901', status: 'Active',
    created_at: '2022-01-15T00:00:00Z', updated_at: now,
  },
  {
    id: 9, clickup_task_id: null,
    full_name: 'Nicole Davis', email: 'nicole@kumon-grn.com', phone: '616-555-2009',
    address: null, date_of_birth: null,
    role: 'Project Manager', hire_date: '2023-03-01', wp_user_id: 16,
    pin: '9012', status: 'Active',
    created_at: '2023-03-01T00:00:00Z', updated_at: now,
  },
];

// ── Attendance (today's mock) ──────────────

export const MOCK_ATTENDANCE: Attendance[] = [
  {
    // Alice — Math+Reading, 60 min, checked in 3:10 PM, SMS sent
    id: 1, student_id: 1,
    check_in: todayAt(15, 10), check_out: null,
    scheduled_time: '3:30 PM', duration_minutes: null,
    checked_in_by: 'Sarah Kim', checked_out_by: null,
    source: 'barcode', notes: null,
    session_duration_minutes: 60,
    session_end_time: addMinutes(todayAt(15, 10), 60),
    sms_10min_sent: true,
    sms_10min_sent_at: addMinutes(todayAt(15, 10), 50),
    sms_recipient_phone: '616-555-1001',
    sms_recipient_name: 'Sarah',
    created_at: todayAt(15, 10),
  },
  {
    // Diana — Math+Reading, 60 min, checked in 3:20 PM, SMS not yet sent
    id: 2, student_id: 4,
    check_in: todayAt(15, 20), check_out: null,
    scheduled_time: '3:20 PM', duration_minutes: null,
    checked_in_by: 'barcode', checked_out_by: null,
    source: 'barcode', notes: null,
    session_duration_minutes: 60,
    session_end_time: addMinutes(todayAt(15, 20), 60),
    sms_10min_sent: false,
    sms_10min_sent_at: null,
    sms_recipient_phone: '616-555-1004',
    sms_recipient_name: 'Diana Sr.',
    created_at: todayAt(15, 20),
  },
  {
    // Fiona — Math+Reading, 60 min, checked in 3:04 PM, SMS sent
    id: 3, student_id: 6,
    check_in: todayAt(15, 4), check_out: null,
    scheduled_time: '3:04 PM', duration_minutes: null,
    checked_in_by: 'barcode', checked_out_by: null,
    source: 'barcode', notes: null,
    session_duration_minutes: 60,
    session_end_time: addMinutes(todayAt(15, 4), 60),
    sms_10min_sent: true,
    sms_10min_sent_at: addMinutes(todayAt(15, 4), 50),
    sms_recipient_phone: '616-555-1006',
    sms_recipient_name: 'Mrs. Glenanne',
    created_at: todayAt(15, 4),
  },
  {
    // Evan — Math only, 30 min, checked in 3:05 PM, SMS sent
    id: 4, student_id: 5,
    check_in: todayAt(15, 5), check_out: null,
    scheduled_time: '3:05 PM', duration_minutes: null,
    checked_in_by: 'barcode', checked_out_by: null,
    source: 'barcode', notes: null,
    session_duration_minutes: 30,
    session_end_time: addMinutes(todayAt(15, 5), 30),
    sms_10min_sent: true,
    sms_10min_sent_at: addMinutes(todayAt(15, 5), 20),
    sms_recipient_phone: '616-555-1005',
    sms_recipient_name: 'Mr. Wright',
    created_at: todayAt(15, 5),
  },
  {
    // Noah — Math+Reading, 60 min, checked in 3:08 PM, SMS not yet sent
    id: 5, student_id: 14,
    check_in: todayAt(15, 8), check_out: null,
    scheduled_time: '3:08 PM', duration_minutes: null,
    checked_in_by: 'barcode', checked_out_by: null,
    source: 'barcode', notes: null,
    session_duration_minutes: 60,
    session_end_time: addMinutes(todayAt(15, 8), 60),
    sms_10min_sent: false,
    sms_10min_sent_at: null,
    sms_recipient_phone: '616-555-1014',
    sms_recipient_name: 'Mrs. Ark',
    created_at: todayAt(15, 8),
  },
  {
    // Peter — Reading only, 30 min, checked in 3:01 PM, SMS sent
    id: 6, student_id: 16,
    check_in: todayAt(15, 1), check_out: null,
    scheduled_time: '3:01 PM', duration_minutes: null,
    checked_in_by: 'barcode', checked_out_by: null,
    source: 'barcode', notes: null,
    session_duration_minutes: 30,
    session_end_time: addMinutes(todayAt(15, 1), 30),
    sms_10min_sent: true,
    sms_10min_sent_at: addMinutes(todayAt(15, 1), 20),
    sms_recipient_phone: '616-555-1016',
    sms_recipient_name: 'Aunt May',
    created_at: todayAt(15, 1),
  },
];

// ── Time Entries (current pay period) ────────────

export const MOCK_TIME_ENTRIES: TimeEntry[] = [
  // Today — currently clocked in
  { id: 1, staff_id: 2, clock_in: todayAt(14, 45), clock_out: null, duration_minutes: null, source: 'kiosk', notes: null, created_at: todayAt(14, 45) },
  { id: 2, staff_id: 3, clock_in: todayAt(14, 50), clock_out: null, duration_minutes: null, source: 'barcode', notes: null, created_at: todayAt(14, 50) },
  { id: 3, staff_id: 4, clock_in: todayAt(15, 0), clock_out: null, duration_minutes: null, source: 'kiosk', notes: null, created_at: todayAt(15, 0) },
  { id: 4, staff_id: 5, clock_in: todayAt(15, 0), clock_out: null, duration_minutes: null, source: 'barcode', notes: null, created_at: todayAt(15, 0) },
  // Yesterday — completed
  { id: 5, staff_id: 1, clock_in: dateAt(daysAgo(1), 14, 0), clock_out: dateAt(daysAgo(1), 19, 0), duration_minutes: 300, source: 'kiosk', notes: null, created_at: dateAt(daysAgo(1), 14, 0) },
  { id: 6, staff_id: 2, clock_in: dateAt(daysAgo(1), 14, 30), clock_out: dateAt(daysAgo(1), 18, 45), duration_minutes: 255, source: 'kiosk', notes: null, created_at: dateAt(daysAgo(1), 14, 30) },
  { id: 7, staff_id: 3, clock_in: dateAt(daysAgo(1), 15, 0), clock_out: dateAt(daysAgo(1), 19, 15), duration_minutes: 255, source: 'barcode', notes: null, created_at: dateAt(daysAgo(1), 15, 0) },
  { id: 8, staff_id: 4, clock_in: dateAt(daysAgo(1), 15, 0), clock_out: dateAt(daysAgo(1), 18, 30), duration_minutes: 210, source: 'kiosk', notes: null, created_at: dateAt(daysAgo(1), 15, 0) },
  // 3 days ago
  { id: 9, staff_id: 1, clock_in: dateAt(daysAgo(3), 14, 0), clock_out: dateAt(daysAgo(3), 19, 30), duration_minutes: 330, source: 'kiosk', notes: null, created_at: dateAt(daysAgo(3), 14, 0) },
  { id: 10, staff_id: 2, clock_in: dateAt(daysAgo(3), 14, 30), clock_out: dateAt(daysAgo(3), 18, 30), duration_minutes: 240, source: 'kiosk', notes: null, created_at: dateAt(daysAgo(3), 14, 30) },
  { id: 11, staff_id: 3, clock_in: dateAt(daysAgo(3), 15, 0), clock_out: dateAt(daysAgo(3), 19, 0), duration_minutes: 240, source: 'barcode', notes: null, created_at: dateAt(daysAgo(3), 15, 0) },
  { id: 12, staff_id: 5, clock_in: dateAt(daysAgo(3), 15, 0), clock_out: dateAt(daysAgo(3), 18, 0), duration_minutes: 180, source: 'kiosk', notes: null, created_at: dateAt(daysAgo(3), 15, 0) },
  // 5 days ago
  { id: 13, staff_id: 1, clock_in: dateAt(daysAgo(5), 14, 0), clock_out: dateAt(daysAgo(5), 19, 0), duration_minutes: 300, source: 'kiosk', notes: null, created_at: dateAt(daysAgo(5), 14, 0) },
  { id: 14, staff_id: 2, clock_in: dateAt(daysAgo(5), 14, 45), clock_out: dateAt(daysAgo(5), 18, 15), duration_minutes: 210, source: 'kiosk', notes: null, created_at: dateAt(daysAgo(5), 14, 45) },
  { id: 15, staff_id: 4, clock_in: dateAt(daysAgo(5), 15, 0), clock_out: dateAt(daysAgo(5), 18, 30), duration_minutes: 210, source: 'manual', notes: 'Forgot to clock in', created_at: dateAt(daysAgo(5), 15, 0) },
];

// ── Student Notes ──────────────────────────

export const MOCK_NOTES: StudentNote[] = [
  {
    id: 1, student_id: 1,
    author_type: 'portal', author_name: 'Sarah Johnson', author_id: 1,
    content: 'Alice felt she struggled with word problems last night. Could she get extra practice?',
    note_date: today, visibility: 'parent',
    created_at: todayAt(8, 15),
  },
  {
    id: 2, student_id: 1,
    author_type: 'admin', author_name: 'Bincy Thomas', author_id: 1,
    content: 'Please ensure she completes a timed test for Math C today.',
    note_date: today, visibility: 'internal',
    created_at: todayAt(14, 30),
  },
  {
    id: 3, student_id: 1,
    author_type: 'staff', author_name: 'Sarah Kim', author_id: 2,
    content: 'Alice did a great job staying focused in Reading today. Completed 5 pages.',
    note_date: today, visibility: 'parent',
    created_at: todayAt(15, 45),
  },
  {
    id: 4, student_id: 4,
    author_type: 'staff', author_name: 'Jane Doe', author_id: 3,
    content: 'Diana is progressing well through E level. Consider advancing to F next week.',
    note_date: today, visibility: 'staff',
    created_at: todayAt(15, 30),
  },
  {
    id: 6, student_id: 1,
    author_type: 'admin', author_name: 'Amy',  author_id: null,
    content: 'Consider moving Alice to Row 3 next week — she works well with Charlie.',
    note_date: today, visibility: 'internal',
    created_at: todayAt(15, 30),
  },
  {
    id: 5, student_id: 9,
    author_type: 'portal', author_name: 'Parent', author_id: null,
    content: 'Ian was coughing this morning. He has his inhaler with him.',
    note_date: today, visibility: 'parent',
    created_at: todayAt(7, 45),
  },
];

// ── Library Books ──────────────────────────

export const MOCK_BOOKS: Book[] = [
  {
    id: 1, title: 'Bob Books: Set 1', author: 'Bobby Lynn Maslen',
    isbn: '978-0439845007', barcode: 'LIB-001',
    category: 'Early Reader', reading_level: '7A-2A',
    status: 'checked-out', type: 'book',
    created_at: '2024-01-01T00:00:00Z', updated_at: now,
  },
  {
    id: 2, title: 'Frog and Toad Are Friends', author: 'Arnold Lobel',
    isbn: '978-0064440202', barcode: 'LIB-002',
    category: 'Early Reader', reading_level: 'AI-AII',
    status: 'available', type: 'book',
    created_at: '2024-01-01T00:00:00Z', updated_at: now,
  },
  {
    id: 3, title: 'Elephant & Piggie: I Really Like Slop!', author: 'Mo Willems',
    isbn: '978-1484722619', barcode: 'LIB-003',
    category: 'Early Reader', reading_level: 'AI-BI',
    status: 'available', type: 'book',
    created_at: '2024-01-01T00:00:00Z', updated_at: now,
  },
  {
    id: 4, title: 'Biscuit Finds a Friend', author: 'Alyssa Satin Capucilli',
    isbn: '978-0064442435', barcode: 'LIB-004',
    category: 'Early Reader', reading_level: '7A-AI',
    status: 'available', type: 'book',
    created_at: '2024-01-01T00:00:00Z', updated_at: now,
  },
  {
    id: 5, title: 'Green Eggs and Ham', author: 'Dr. Seuss',
    isbn: '978-0394800165', barcode: 'LIB-005',
    category: 'Early Reader', reading_level: 'AI-AII',
    status: 'available', type: 'book',
    created_at: '2024-01-01T00:00:00Z', updated_at: now,
  },
  {
    id: 6, title: 'Charlotte\'s Web', author: 'E.B. White',
    isbn: '978-0064400558', barcode: 'LIB-006',
    category: 'Chapter Book', reading_level: 'CI-DI',
    status: 'checked-out', type: 'book',
    created_at: '2024-01-01T00:00:00Z', updated_at: now,
  },
  {
    id: 7, title: 'Magic Tree House #1', author: 'Mary Pope Osborne',
    isbn: '978-0679824114', barcode: 'LIB-007',
    category: 'Chapter Book', reading_level: 'BII-CI',
    status: 'available', type: 'book',
    created_at: '2024-01-01T00:00:00Z', updated_at: now,
  },
  // Answer Keys
  {
    id: 101, title: 'Math Level D Answer Key', author: null,
    isbn: null, barcode: 'AK-001',
    category: 'Reference', reading_level: 'D',
    status: 'checked-out', type: 'answer_key',
    created_at: '2024-01-01T00:00:00Z', updated_at: now,
  },
  {
    id: 102, title: 'Math Level F Answer Key', author: null,
    isbn: null, barcode: 'AK-002',
    category: 'Reference', reading_level: 'F',
    status: 'available', type: 'answer_key',
    created_at: '2024-01-01T00:00:00Z', updated_at: now,
  },
  {
    id: 103, title: 'Reading Level GI Answer Key', author: null,
    isbn: null, barcode: 'AK-003',
    category: 'Reference', reading_level: 'GI',
    status: 'checked-out', type: 'answer_key',
    created_at: '2024-01-01T00:00:00Z', updated_at: now,
  },
  {
    id: 104, title: 'Math Level H Answer Key', author: null,
    isbn: null, barcode: 'AK-004',
    category: 'Reference', reading_level: 'H',
    status: 'available', type: 'answer_key',
    created_at: '2024-01-01T00:00:00Z', updated_at: now,
  },
  {
    id: 105, title: 'Reading Level CII Answer Key', author: null,
    isbn: null, barcode: 'AK-005',
    category: 'Reference', reading_level: 'CII',
    status: 'checked-out', type: 'answer_key',
    created_at: '2024-01-01T00:00:00Z', updated_at: now,
  },
  {
    id: 106, title: 'Math Level 3A Answer Key', author: null,
    isbn: null, barcode: 'AK-006',
    category: 'Reference', reading_level: '3A',
    status: 'available', type: 'answer_key',
    created_at: '2024-01-01T00:00:00Z', updated_at: now,
  },
];

// ── Book Loans ─────────────────────────────

export const MOCK_BOOK_LOANS: BookLoan[] = [
  // Outstanding loans
  {
    id: 1, book_id: 1, student_id: 2,
    checked_out_at: dateAt(daysAgo(3), 15, 30), due_date: twoWeeksFromNow(),
    returned_at: null, checked_out_by: 'Sarah Kim', returned_to: null,
    created_at: dateAt(daysAgo(3), 15, 30),
  },
  {
    id: 2, book_id: 6, student_id: 9,
    checked_out_at: dateAt(daysAgo(10), 16, 0), due_date: daysAgo(3), // Overdue!
    returned_at: null, checked_out_by: 'Jane Doe', returned_to: null,
    created_at: dateAt(daysAgo(10), 16, 0),
  },
  // Returned loans (history)
  {
    id: 3, book_id: 2, student_id: 1,
    checked_out_at: dateAt(daysAgo(20), 15, 0), due_date: daysAgo(6),
    returned_at: dateAt(daysAgo(8), 15, 30), checked_out_by: 'Sarah Kim', returned_to: 'Jane Doe',
    created_at: dateAt(daysAgo(20), 15, 0),
  },
  {
    id: 4, book_id: 5, student_id: 4,
    checked_out_at: dateAt(daysAgo(15), 16, 0), due_date: daysAgo(1),
    returned_at: dateAt(daysAgo(5), 15, 45), checked_out_by: 'Mike Rodriguez', returned_to: 'Sarah Kim',
    created_at: dateAt(daysAgo(15), 16, 0),
  },
  {
    id: 5, book_id: 7, student_id: 3,
    checked_out_at: dateAt(daysAgo(25), 15, 30), due_date: daysAgo(11),
    returned_at: dateAt(daysAgo(12), 16, 0), checked_out_by: 'Jane Doe', returned_to: 'Leah Martin',
    created_at: dateAt(daysAgo(25), 15, 30),
  },
  {
    id: 6, book_id: 3, student_id: 8,
    checked_out_at: dateAt(daysAgo(7), 15, 15), due_date: daysAgo(0),
    returned_at: dateAt(daysAgo(2), 16, 30), checked_out_by: 'Leah Martin', returned_to: 'Sarah Kim',
    created_at: dateAt(daysAgo(7), 15, 15),
  },
  // Answer key loans
  {
    id: 7, book_id: 101, student_id: 4,
    checked_out_at: dateAt(daysAgo(2), 15, 0), due_date: twoWeeksFromNow(),
    returned_at: null, checked_out_by: 'Sarah Kim', returned_to: null,
    created_at: dateAt(daysAgo(2), 15, 0),
  },
  {
    id: 8, book_id: 103, student_id: 1,
    checked_out_at: dateAt(daysAgo(5), 16, 0), due_date: twoWeeksFromNow(),
    returned_at: null, checked_out_by: 'Jane Doe', returned_to: null,
    created_at: dateAt(daysAgo(5), 16, 0),
  },
  {
    id: 9, book_id: 105, student_id: 6,
    checked_out_at: dateAt(daysAgo(1), 15, 30), due_date: twoWeeksFromNow(),
    returned_at: null, checked_out_by: 'Mike Rodriguez', returned_to: null,
    created_at: dateAt(daysAgo(1), 15, 30),
  },
];

// ── Row Assignments (today) ────────────────

export const MOCK_ROW_ASSIGNMENTS: RowAssignment[] = [
  { id: 1, student_id: 1, row_number: 3, assigned_date: today, assigned_by: 2, created_at: todayAt(14, 0) },
  { id: 2, student_id: 4, row_number: 3, assigned_date: today, assigned_by: 2, created_at: todayAt(14, 0) },
  { id: 3, student_id: 6, row_number: 3, assigned_date: today, assigned_by: 2, created_at: todayAt(14, 0) },
  { id: 4, student_id: 14, row_number: 3, assigned_date: today, assigned_by: 2, created_at: todayAt(14, 0) },
  { id: 5, student_id: 16, row_number: 3, assigned_date: today, assigned_by: 2, created_at: todayAt(14, 0) },
  { id: 6, student_id: 5, row_number: 3, assigned_date: today, assigned_by: 2, created_at: todayAt(14, 0) },
  { id: 7, student_id: 2, row_number: 1, assigned_date: today, assigned_by: 2, created_at: todayAt(14, 0) },
  { id: 8, student_id: 3, row_number: 1, assigned_date: today, assigned_by: 2, created_at: todayAt(14, 0) },
  { id: 9, student_id: 7, row_number: 2, assigned_date: today, assigned_by: 2, created_at: todayAt(14, 0) },
  { id: 10, student_id: 8, row_number: 2, assigned_date: today, assigned_by: 2, created_at: todayAt(14, 0) },
  { id: 11, student_id: 9, row_number: 4, assigned_date: today, assigned_by: 2, created_at: todayAt(14, 0) },
  { id: 12, student_id: 10, row_number: 4, assigned_date: today, assigned_by: 2, created_at: todayAt(14, 0) },
  { id: 13, student_id: 11, row_number: 5, assigned_date: today, assigned_by: 2, created_at: todayAt(14, 0) },
  { id: 14, student_id: 12, row_number: 5, assigned_date: today, assigned_by: 2, created_at: todayAt(14, 0) },
  { id: 15, student_id: 13, row_number: 6, assigned_date: today, assigned_by: 2, created_at: todayAt(14, 0) },
  { id: 16, student_id: 15, row_number: 6, assigned_date: today, assigned_by: 2, created_at: todayAt(14, 0) },
];

// ── Center Settings ──────────────────────
// Capacity set to 8 for mock mode so stoplight colors are visible with 16 students

export const MOCK_CENTER_SETTINGS: CenterSettings = {
  center_capacity: 66,
  operating_days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday'],
  time_slots: generateTimeSlots({
    Monday: { start: 1500, end: 1900 },
    Tuesday: { start: 1500, end: 1800 },
    Wednesday: { start: 1500, end: 1800 },
    Thursday: { start: 1500, end: 1900 },
  }),
  staff_student_ratio: 3,
};

// ── Staff Slot Assignments (recurring weekly schedule) ──

export const MOCK_STAFF_SLOTS: StaffSlotAssignment[] = [
  // Monday
  { id: 1, staff_id: 2, day_of_week: 'Monday', time_sort_key: 1500, effective_from: '2025-01-01', effective_to: null, created_at: now },
  { id: 2, staff_id: 3, day_of_week: 'Monday', time_sort_key: 1500, effective_from: '2025-01-01', effective_to: null, created_at: now },
  { id: 3, staff_id: 4, day_of_week: 'Monday', time_sort_key: 1530, effective_from: '2025-01-01', effective_to: null, created_at: now },
  { id: 4, staff_id: 3, day_of_week: 'Monday', time_sort_key: 1600, effective_from: '2025-01-01', effective_to: null, created_at: now },
  { id: 5, staff_id: 5, day_of_week: 'Monday', time_sort_key: 1630, effective_from: '2025-01-01', effective_to: null, created_at: now },
  // Tuesday
  { id: 6, staff_id: 2, day_of_week: 'Tuesday', time_sort_key: 1500, effective_from: '2025-01-01', effective_to: null, created_at: now },
  { id: 7, staff_id: 4, day_of_week: 'Tuesday', time_sort_key: 1530, effective_from: '2025-01-01', effective_to: null, created_at: now },
  { id: 8, staff_id: 3, day_of_week: 'Tuesday', time_sort_key: 1600, effective_from: '2025-01-01', effective_to: null, created_at: now },
  // Wednesday
  { id: 9, staff_id: 2, day_of_week: 'Wednesday', time_sort_key: 1500, effective_from: '2025-01-01', effective_to: null, created_at: now },
  { id: 10, staff_id: 3, day_of_week: 'Wednesday', time_sort_key: 1500, effective_from: '2025-01-01', effective_to: null, created_at: now },
  { id: 11, staff_id: 4, day_of_week: 'Wednesday', time_sort_key: 1530, effective_from: '2025-01-01', effective_to: null, created_at: now },
  { id: 12, staff_id: 5, day_of_week: 'Wednesday', time_sort_key: 1600, effective_from: '2025-01-01', effective_to: null, created_at: now },
  // Thursday
  { id: 13, staff_id: 2, day_of_week: 'Thursday', time_sort_key: 1500, effective_from: '2025-01-01', effective_to: null, created_at: now },
  { id: 14, staff_id: 4, day_of_week: 'Thursday', time_sort_key: 1530, effective_from: '2025-01-01', effective_to: null, created_at: now },
  { id: 15, staff_id: 3, day_of_week: 'Thursday', time_sort_key: 1600, effective_from: '2025-01-01', effective_to: null, created_at: now },
  { id: 16, staff_id: 5, day_of_week: 'Thursday', time_sort_key: 1630, effective_from: '2025-01-01', effective_to: null, created_at: now },
];

// ── Schedule Overrides (this week) ──────

function thisWeekDate(dayOffset: number): string {
  const d = new Date();
  const dayOfWeek = d.getDay();
  const mondayOffset = dayOfWeek === 0 ? -6 : 1 - dayOfWeek;
  d.setDate(d.getDate() + mondayOffset + dayOffset);
  return d.toISOString().split('T')[0];
}

export const MOCK_SCHEDULE_OVERRIDES: ScheduleOverride[] = [
  {
    // Ben (TuTh 1530) → makeup class on Monday at 1530
    id: 1, student_id: 2, override_type: 'add',
    original_day: null, original_time: null,
    new_day: 'Monday', new_time: 1530,
    effective_date: thisWeekDate(0), // Monday
    reason: 'Makeup class',
    created_at: now,
  },
  {
    // Alice (MW 1500) → absent Wednesday for vacation
    id: 2, student_id: 1, override_type: 'remove',
    original_day: 'Wednesday', original_time: 1500,
    new_day: null, new_time: null,
    effective_date: thisWeekDate(2), // Wednesday
    reason: 'Family vacation',
    created_at: now,
  },
  {
    // Liam (MW 1600) → moved to 1530 on Monday
    id: 3, student_id: 12, override_type: 'move',
    original_day: 'Monday', original_time: 1600,
    new_day: 'Monday', new_time: 1530,
    effective_date: thisWeekDate(0), // Monday
    reason: 'Schedule conflict',
    created_at: now,
  },
];

// ── Classroom Configuration (state-driven, configurable per center) ──

export const MOCK_CLASSROOM_CONFIG: ClassroomSection[] = [
  {
    id: 'sec-el', name: 'Early Learners',
    desc: '1:2 teacher-to-student ratio',
    color: 'var(--secondary)',
    rows: [
      { id: 'el1', label: 'EL Row 1', tables: 1, seatsPerTable: 2, teacher: 'Maria T.', ratio: '1:2' },
      { id: 'el2', label: 'EL Row 2', tables: 1, seatsPerTable: 2, teacher: 'Lisa W.', ratio: '1:2' },
      { id: 'el3', label: 'EL Row 3', tables: 1, seatsPerTable: 2, teacher: 'Tom H.', ratio: '1:2' },
    ],
  },
  {
    id: 'sec-main', name: 'Main Classroom',
    desc: 'Standard rows',
    color: 'var(--primary)',
    rows: [
      { id: 'm1', label: 'Row 1', tables: 5, seatsPerTable: 2, teacher: 'Sarah K.' },
      { id: 'm2', label: 'Row 2', tables: 5, seatsPerTable: 2, teacher: 'Jane D.' },
      { id: 'm3', label: 'Row 3', tables: 5, seatsPerTable: 2, teacher: 'Mike R.' },
      { id: 'm4', label: 'Row 4', tables: 5, seatsPerTable: 2, teacher: 'Leah M.' },
      { id: 'm5', label: 'Row 5', tables: 5, seatsPerTable: 2, teacher: 'Chris P.' },
    ],
  },
  {
    id: 'sec-upper', name: 'Upper Classroom',
    desc: 'Advanced students — requires advanced math teacher',
    color: 'var(--accent)',
    rows: [
      { id: 'upper', label: 'Upper Row', tables: 5, seatsPerTable: 2, teacher: 'Dr. Kim (Adv. Math)', advanced: true },
    ],
  },
];
